/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as LogosIndexRouteImport } from './routes/logos.index'
import { Route as LogosDirectionRouteImport } from './routes/logos.$direction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosIndexRoute = LogosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogosRoute,
} as any)
const LogosDirectionRoute = LogosDirectionRouteImport.update({
  id: '/$direction',
  path: '/$direction',
  getParentRoute: () => LogosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/compare': typeof CompareRoute
  '/logos': typeof LogosRouteWithChildren
  '/review': typeof ReviewRoute
  '/thanks': typeof ThanksRoute
  '/typography': typeof TypographyRoute
  '/logos/$direction': typeof LogosDirectionRoute
  '/logos/': typeof LogosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/compare': typeof CompareRoute
  '/review': typeof ReviewRoute
  '/thanks': typeof ThanksRoute
  '/typography': typeof TypographyRoute
  '/logos/$direction': typeof LogosDirectionRoute
  '/logos': typeof LogosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/compare': typeof CompareRoute
  '/logos': typeof LogosRouteWithChildren
  '/review': typeof ReviewRoute
  '/thanks': typeof ThanksRoute
  '/typography': typeof TypographyRoute
  '/logos/$direction': typeof LogosDirectionRoute
  '/logos/': typeof LogosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colors'
    | '/compare'
    | '/logos'
    | '/review'
    | '/thanks'
    | '/typography'
    | '/logos/$direction'
    | '/logos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colors'
    | '/compare'
    | '/review'
    | '/thanks'
    | '/typography'
    | '/logos/$direction'
    | '/logos'
  id:
    | '__root__'
    | '/'
    | '/colors'
    | '/compare'
    | '/logos'
    | '/review'
    | '/thanks'
    | '/typography'
    | '/logos/$direction'
    | '/logos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorsRoute: typeof ColorsRoute
  CompareRoute: typeof CompareRoute
  LogosRoute: typeof LogosRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  ThanksRoute: typeof ThanksRoute
  TypographyRoute: typeof TypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos/': {
      id: '/logos/'
      path: '/'
      fullPath: '/logos/'
      preLoaderRoute: typeof LogosIndexRouteImport
      parentRoute: typeof LogosRoute
    }
    '/logos/$direction': {
      id: '/logos/$direction'
      path: '/$direction'
      fullPath: '/logos/$direction'
      preLoaderRoute: typeof LogosDirectionRouteImport
      parentRoute: typeof LogosRoute
    }
  }
}

interface LogosRouteChildren {
  LogosDirectionRoute: typeof LogosDirectionRoute
  LogosIndexRoute: typeof LogosIndexRoute
}

const LogosRouteChildren: LogosRouteChildren = {
  LogosDirectionRoute: LogosDirectionRoute,
  LogosIndexRoute: LogosIndexRoute,
}

const LogosRouteWithChildren = LogosRoute._addFileChildren(LogosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorsRoute: ColorsRoute,
  CompareRoute: CompareRoute,
  LogosRoute: LogosRouteWithChildren,
  ReviewRoute: ReviewRoute,
  ThanksRoute: ThanksRoute,
  TypographyRoute: TypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
